seed: 0
model:
    arch: nasunet
data:
    dataset: promise12
    train_split: train_aug
    split: val
    img_rows: 'same'
    img_cols: 'same'
searching:
    init_channels: 32
    depth: 4
    epoch: 500
    batch_size: 16
#    batch_size: 6
#    batch_size: 4
    report_freq: 20
    n_workers: 2
    alpha_begin: 15
    max_patience: 50
    gpu: True
    multi_gpus: True
    sharing_normal: False
    double_down_channel: False
    meta_node_num: 3
    grad_clip: 5
    train_portion: 0.5
    model_optimizer:
        name: 'sgd'
        lr: 0.025
        weight_decay: 3.0e-4
    arch_optimizer:
        name: 'adam'
        lr: 3.0e-4
        weight_decay: 5.0e-3
    loss:
#        name: 'dice_sq_ce'
        name: 'dice_ce'
        size_average: False
        aux_weight:
    resume:
training:
    geno_type: NASUNET
    init_channels: 32
    depth: 6
    epoch: 3600
#    batch_size: 26
#    batch_size: 16
    batch_size: 10
#    batch_size: 3
    report_freq: 10
    n_workers: 2
    multi_gpus: False
    double_down_channel: False
    grad_clip: 3
    max_patience: 100
    model_optimizer:
        name: 'adam'
        lr: 1.0e-3
        weight_decay: 5.0e-4
    loss:
#        name: 'dice_sq_ce'
        name: 'dice_ce'
        aux_weight: 0
    backbone:
    lr_schedule:
        name: 'cos'
        T_max: 100
    resume:
