seed: 0
model:
    arch: nas-unet
data:
    dataset: chaos
    train_split: train_aug
    split: val
    img_rows: 'same'
    img_cols: 'same'
searching:
    init_channels: 32
    depth: 5
    epoch: 1000
    batch_size: 20
#    batch_size: 12
#    batch_size: 3
    report_freq: 10
    n_workers: 2
    alpha_begin: 15
    max_patience: 50
    gpu: True
    multi_gpus: True
    sharing_normal: True
    double_down_channel: False
    deep_supervision: False
    meta_node_num: 2
    grad_clip: 5
    train_portion: 0.5
    model_optimizer:
        name: 'sgd'
        lr: 0.025
        weight_decay: 3.0e-4
        momentum: 0.9
#        name: 'adabound'
#        lr: 1.0e-3
#        weight_decay: 5.0e-4
    arch_optimizer:
        name: 'adam'
#        lr: 3.0e-4
        lr: 1.0e-4
#        weight_decay: 5.0e-3
        weight_decay: 1.0e-3
        betas: !!python/tuple [ 0.5, 0.999 ]
    loss:
        name: 'dice_ce'
        size_average: False
    resume:
training:
    geno_type: NASUNET
    init_channels: 32
    depth: 5
    epoch: 3600
    batch_size: 12
    report_freq: 10
    n_workers: 2
    multi_gpus: True
    double_down_channel: False
    deep_supervision: False
    grad_clip: 5
    max_patience: 200
    model_optimizer:
        name: 'sgd'
        lr: 6.0e-3
        weight_decay: 5.0e-4
        momentum: 0.9
#        name: 'adabound'
#        lr: 1.0e-3
#        weight_decay: 5.0e-4
    loss:
        name: 'dice_ce'
    backbone:
    lr_schedule:
        name: 'cos'
        T_max: 100
#        name: 'exp_lr'
#        gamma: 0.995
    resume:
